INSERT INTO SAMPLE_DATA.SAMPLE_ENTITY(MESSAGE) VALUES ('message1');
INSERT INTO SAMPLE_DATA.SAMPLE_ENTITY(MESSAGE) VALUES ('message2');
INSERT INTO SAMPLE_DATA.SAMPLE_ENTITY(MESSAGE) VALUES ('message3');
