CREATE SCHEMA IF NOT EXISTS SAMPLE_DATA;
CREATE SEQUENCE IF NOT EXISTS SAMPLE_DATA.SAMPLE_ENTITY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS SAMPLE_DATA.SAMPLE_ENTITY (
    id NUMBER DEFAULT SAMPLE_DATA.SAMPLE_ENTITY_SEQ.NEXTVAL PRIMARY KEY,
    message VARCHAR(1024)
);
